server:
  port: 8081

spring:
  application:
     name:  My_Crud_App
     
  datasource:
    url: jdbc:mysql://localhost:3306/CrudAppDatabase
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jaiswal
    
    
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true
    
  
